### PR TITLE
Add missing dry/core/equalizer requires

### PR DESCRIPTION
**Pull request by timriley**
Putting these in any file where we refer to Dry::Equalizer should prevent `undefined method 'Equalizer' for Dry:Module` occurring, regardless of the order of requires.

@solnic @flash-gordon Is there any reason these weren't here before? We get the error above today in CI when upgrading a work project to 1.5.0.

### CODE REVIEW

**Comment by solnic** [comment]
> @solnic @flash-gordon Is there any reason these weren't here before?

no, this was missed by an accident and now it's been revealed due to moving to dry-core

**Review by solnic — APPROVED** [review]

**Review by flash-gordon — APPROVED** [review]
I am wondering why it worked before. @timriley how do you `require` dry-types?

**Comment by timriley** [comment]
Thanks folks :) Am releasing this as 1.5.1 now. I confirmed it fixed our build issue earlier today. I'll check back to work out how we're loading dry-types tomorrow. It's within a Rails app.

**Comment by solnic** [comment]
@timriley FWIW - I don't think this was anything unexpected, it just happened that in your case files were loaded previously in such an order that the equalizer happened to be already loaded before loading dry-types.
